image:
   file: .gitpod.dockerfile
tasks:
  - prebuild: cp -R  ~/group-project-frontend-template/node_modules .
    before:  npm-install-missing
    command: ng serve --port 8000
ports:
  - port: 8000
    onOpen: open-preview
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
